# additional ftp server for testing ftp connectivity
services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      USERS: "user|pass|/Users/ftp_path"
    volumes:
      - ${PWD}/smf:/Users/ftp_path
