services:
  smf:
    container_name: ${APP_NAME:-smf}_apache
    build:
      dockerfile: Dockerfile
      args:
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-apache}
    image: smf:${BASE_IMAGE_TAG:-apache}
    ports:
      - "${SMF_PORT:-8500}:80"
    environment:
      - TZ
    volumes:
    - ${PWD}/smf:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:${DB_TAG:-latest}
    container_name: ${APP_NAME:-smf}_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
