services:
  smf:
    container_name: ${APP_NAME:-smf}_apache
    build:
      context: .
      args:
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-7.1-apache}
    image: smf:test
    ports:
      - "${SMF_PORT:-8500}:80"
    environment:
      - TZ
    volumes:
    - ${PWD}/smf:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:${DB_TAG:-10.0}
    container_name: ${APP_NAME:-smf}_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
