services:
  smf:
    container_name: ${APP_NAME}_apache
    build:
      context: .
      args:
        BASE_IMAGE_TAG: 7.1-apache
    image: smf:test
    ports:
      - "${SMF_PORT}:80"
    environment:
      - TZ
    volumes:
    - ${PWD}/smf:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    container_name: ${APP_NAME}_mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
